name: foodly
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  cached_network_image: ^3.4.1
  country_picker: ^2.0.23
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  firebase_app_check: ^0.3.1+3
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.0
  firebase_core_platform_interface: ^5.3.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_otp_text_field: ^1.2.0
  flutter_polyline_points: ^2.0.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.9
  flutter_vector_icons: ^2.0.0
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  get: ^4.6.6
  get_storage: ^2.1.1
  glass: ^1.0.2+1
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.9.0
  http: ^1.1.0
  lottie: ^2.7.0
  otp_text_field: ^1.1.3
  phone_otp_verification: ^1.0.3
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/anime/
    - assets/icons/
