name: restaurant_foodly
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  firebase_app_check: ^0.3.1+3
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  firebase_storage: ^12.3.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  flutter_vector_icons: ^2.0.0
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.9.0
  http: ^1.2.2
  image_picker: ^1.1.2
  lottie: ^3.1.2
  otp_text_field: ^1.1.3
  otp_text_field_v2: ^1.0.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/anime/
    - assets/icons/
